analyzer:
  errors:
    avoid_bool_literals_in_conditional_expressions: ignore
    avoid_renaming_method_parameters: ignore
    public_member_api_docs: ignore
include: package:very_good_analysis/analysis_options.yaml
