name: education_project
description: "A new Flutter project."
publish_to: ""
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  chewie: 1.7.5
  cloud_firestore: ^4.15.8
  coverage: ^1.6.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  fake_cloud_firestore: ^2.4.8
  file_picker: 
  firebase_auth: ^4.17.8
  firebase_auth_mocks: 0.9.2
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  firebase_storage_mocks: ^0.6.1
  firebase_ui_auth: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  get_it: 
  google_fonts: ^4.0.4
  google_sign_in_mocks: ^0.3.0
  iconly: ^1.0.1
  image_picker: 
  intl: 
  lottie: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.6
  url_launcher: ^6.3.0
  video_thumbnail: ^0.5.3
  youtube_metadata: ^1.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: 

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/vectors/

  # fonts:
  # - family: Roboto
  #   fonts:
  #     - asset: assets/fonts/Roboto-Regular.ttf
  # - family: OpenSans
  #   fonts:
  #     - asset: assets/fonts/OpenSans-Regular.ttf
  # - family: Lato
  #   fonts:
  #     - asset: assets/fonts/Lato-Regular.ttf
  # - family: Montserrat
  #   fonts:
  #     - asset: assets/fonts/Montserrat-Regular.ttf
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins-Regular.ttf
