// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkYaqKOn8eziSAkiDHExkBFj3AkN-iy8',
    appId: '1:351115711488:web:e46fa4342af728bb9ef4e5',
    messagingSenderId: '351115711488',
    projectId: 'education-project-bdd5c',
    authDomain: 'education-project-bdd5c.firebaseapp.com',
    storageBucket: 'education-project-bdd5c.appspot.com',
    measurementId: 'G-WFCBN7GHVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1iF83oa1cncE5dUBXU8lM9QyalgA6grA',
    appId: '1:351115711488:android:370dfbe4590b23679ef4e5',
    messagingSenderId: '351115711488',
    projectId: 'education-project-bdd5c',
    storageBucket: 'education-project-bdd5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAje-P-6yMdomKLz0q-ru0MfXZNiJ5xGlg',
    appId: '1:351115711488:ios:67ae9b90cfe1aeb49ef4e5',
    messagingSenderId: '351115711488',
    projectId: 'education-project-bdd5c',
    storageBucket: 'education-project-bdd5c.appspot.com',
    iosBundleId: 'com.example.educationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAje-P-6yMdomKLz0q-ru0MfXZNiJ5xGlg',
    appId: '1:351115711488:ios:67ae9b90cfe1aeb49ef4e5',
    messagingSenderId: '351115711488',
    projectId: 'education-project-bdd5c',
    storageBucket: 'education-project-bdd5c.appspot.com',
    iosBundleId: 'com.example.educationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkkYaqKOn8eziSAkiDHExkBFj3AkN-iy8',
    appId: '1:351115711488:web:96aa5acde812714d9ef4e5',
    messagingSenderId: '351115711488',
    projectId: 'education-project-bdd5c',
    authDomain: 'education-project-bdd5c.firebaseapp.com',
    storageBucket: 'education-project-bdd5c.appspot.com',
    measurementId: 'G-JKL5HG5GVZ',
  );
}
